### ISSUE TITLE
nbval does not show up as plugin in a fresh env

### ISSUE THREAD

**Issue by marscher** [conda-forge/nbval-feedstock#3]
Hi,

by creating a new environment like this:
`conda create -n test_nbval nbval -y`
This also installes pytest in the given environment.

Now invoking it
```
. activate test_nbval
pytest --nbval
```
I get the message, that nbval is an unknown subcommand:
```
usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: --nbval
  inifile: None
  rootdir: ...
```

It is absolutely not clear, why this does not work, because the recipe is fairly standard. Maybe we can add a test, which tries to invoke py.test --nbval on a one celled (hello world) notebook?

**Comment by marscher** [comment]
@conda-forge/core This bug has been caused by just merging the automatically generated version bump PR by one of CFs bots without checking new dependencies. I think it would be a nice improvement to check if install_requires has changed for python packages. Most package names are equal for CF and PyPI, aren't they. I just do not know how to handle packages with different names but same content. Cheers - thanks for reading.

**Comment by marscher** [comment]
Hashing this list and comparing it would be sufficient to generate a big fat warning for the pkg maintainer to take extra care. The hash could be stored in a git tag (eg. with the same version number as the pkg it self). What do you think?

**Comment by CJ-Wright** [comment]
xref: https://github.com/regro/cf-scripts/issues/22
